"use client";
import { useEffect, useRef, useState } from "react";

const CONFIG = {
  label: "CORE CAPABILITIES",
  heading: "Six pillars. One governed operating layer.",
  description:
    "Not a feature wall. A structured operating system where every capability serves a defined job within the governed execution chain.",

  cards: [
    {
      title: "AI-Guided Strategy",
      description:
        "Campaign planning, channel intelligence, and performance recommendations generated by the Strategy Agent — connected to Brand Library rules and approval workflows.",
      tags: "Strategy Agent · Knowledge Hub",
      iconColor: "#20E7F2",
      icon: (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
          <circle cx="12" cy="12" r="10"/>
          <line x1="2" y1="12" x2="22" y2="12"/>
          <path d="M12 2a15.3 15.3 0 014 10 15.3 15.3 0 01-4 10 15.3 15.3 0 01-4-10 15.3 15.3 0 014-10z"/>
        </svg>
      ),
    },
    {
      title: "Content Operations",
      description:
        "Content briefs, drafts, variants, and media coordination from brief to published output. Content Agent assists creation; Review Queue captures the approval chain.",
      tags: "Content Studio · Publishing Calendar",
      iconColor: "#C9A84C",
      icon: (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
          <path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 013 3L7 19l-4 1 1-4L16.5 3.5z"/>
        </svg>
      ),
    },
    {
      title: "Brand Governance",
      description:
        "Brand Library captures voice guidelines, approved claims, prohibited phrases, visual standards, and regional rules — applied as policy checks before any content reaches review.",
      tags: "Brand Library · Policy Center",
      iconColor: "#C9A84C",
      icon: (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
          <rect x="3" y="3" width="7" height="9" rx="1"/>
          <rect x="14" y="3" width="7" height="5" rx="1"/>
          <rect x="14" y="12" width="7" height="9" rx="1"/>
          <rect x="3" y="16" width="7" height="5" rx="1"/>
        </svg>
      ),
    },
    {
      title: "Approval Control",
      description:
        "Review Queue, Validation Desk, Approvals, separation of duties, and locked actions with plain-English reasons. Every authorized output carries an immutable approval record.",
      tags: "Review Queue · Validation Desk",
      iconColor: "#20E7F2",
      icon: (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
          <polyline points="23 4 23 10 17 10"/>
          <path d="M20.49 15a9 9 0 11-2.12-9.36L23 10"/>
        </svg>
      ),
    },
    {
      title: "Engagement Operations",
      description:
        "Governed inbox for comments, DMs, and mentions. Routing by brand, channel, risk level, and escalation status. Sensitive interactions escalated before any response is sent.",
      tags: "Inbox / Engagement · Crisis routing",
      iconColor: "#20E7F2",
      icon: (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
          <path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/>
        </svg>
      ),
    },
    {
      title: "Evidence & Revenue Intelligence",
      description:
        "Immutable audit events, watermarked evidence exports, performance attribution by channel, and ROI reporting connected directly to campaign decisions.",
      tags: "Analytics & ROI · Audit & Evidence",
      iconColor: "#22C55E",
      icon: (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
          <line x1="18" y1="20" x2="18" y2="10"/>
          <line x1="12" y1="20" x2="12" y2="4"/>
          <line x1="6" y1="20" x2="6" y2="14"/>
        </svg>
      ),
    },
  ],
};

export default function PlatformCapabilities() {
  const [visible, setVisible] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setVisible(true); },
      { threshold: 0.1 }
    );
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, []);

  return (
    <section className="bg-[#0C1422] py-24 px-6">
      <div ref={ref} className="max-w-[1200px] mx-auto">

        {/* Header */}
        <div
          className={`text-center mb-16 transition-all duration-700 ease-out ${
            visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-8"
          }`}
        >
          <p className="text-[#C9A84C] text-xs font-bold tracking-widest uppercase mb-4 flex items-center justify-center gap-2">
            <span className="w-6 h-px bg-white/40 inline-block" /> Core Capabilities
          </p>
          <h2 className="text-4xl lg:text-5xl font-black text-white leading-tight max-w-2xl mx-auto mb-5">
            {CONFIG.heading}
          </h2>
          <p className="text-white/40 text-sm leading-relaxed max-w-xl mx-auto">
            {CONFIG.description}
          </p>
        </div>

        {/* 3x2 Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {CONFIG.cards.map((card, i) => (
            <div
              key={card.title}
              className={`group relative border border-[#FFFFFF1A] rounded-xl p-6 bg-[#0C1422] cursor-default
                transition-all duration-500 ease-out hover:bg-[#0d0d20] hover:border-white/20 hover:-translate-y-1
                ${visible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-10"}`}
              style={{
                transitionDelay: `${150 + i * 100}ms`,
              }}
            >
              <div
                className="w-11 h-11 rounded-lg flex items-center justify-center mb-6 bg-[#0C1422] border border-[#FFFFFF1A] transition-transform duration-300 group-hover:scale-110"
                style={{ color: card.iconColor }}
              >
                {card.icon}
              </div>

              {/* Title */}
              <h3 className="text-white text-base font-bold mb-2">
                {card.title}
              </h3>

              {/* Description */}
              <p className="text-white/40 text-xs leading-relaxed mb-6">
                {card.description}
              </p>


              <div className="mt-auto">
                <span className="text-xs px-3 py-1 rounded-md border border-[#20E7F226] bg-[#20E7F20F] text-[#20E7F2]">
                  {card.tags}
                </span>
              </div>
            </div>
          ))}
        </div>

      </div>
    </section>
  );
}