"use client";

import React, { useState } from "react";
import { motion, Variants } from "framer-motion";
import { Download } from "lucide-react";

const containerVariants: Variants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.6,
      staggerChildren: 0.1,
    },
  },
};

const itemVariants: Variants = {
  hidden: { opacity: 0, y: 14 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, ease: "easeOut" },
  },
};

export default function ZoikoExecutiveReportSection() {
  const [email, setEmail] = useState("");
  const [company, setCompany] = useState("");
  const [role, setRole] = useState("");
  const [teamSize, setTeamSize] = useState("");

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
  };

  return (
    <section className="relative w-full bg-[#F4F6FB] py-16 md:py-24 px-6 font-sans text-[#1a1a1a]">
      <motion.div
        variants={containerVariants}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, margin: "-50px" }}
        className="max-w-6xl mx-auto space-y-12"
      >
        {/* Section Header */}
        <div className="space-y-3">
          <motion.div
            variants={itemVariants}
            className="flex items-center gap-2"
          >
            <span className="h-px w-6 bg-[#68758A]" />
            <span className="text-xs font-mono tracking-widest text-[#68758A] uppercase">
              EXECUTIVE REPORT
            </span>
          </motion.div>

          <motion.h2
            variants={itemVariants}
            className="text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight text-[#1a1a1a] leading-tight"
          >
            CFO-ready output for your buying committee.
          </motion.h2>

          <motion.p
            variants={itemVariants}
            className="text-sm sm:text-base leading-relaxed text-[#272727]/80 max-w-xl"
          >
            The sample executive report shows what procurement, finance, and
            legal receive: inputs, assumptions, outputs, governance value,
            payback period, and recommended next steps.
          </motion.p>
        </div>

        {/* 2-Column Grid Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          {/* Left Column: Sample Report Preview Card (7 Cols) */}
          <motion.div variants={itemVariants} className="lg:col-span-7">
            <div className="rounded-2xl bg-white  shadow-xl overflow-hidden">
              {/* Report Header Bar */}
              <div className="bg-[#0f1723] px-6 py-3.5 flex items-center justify-between">
                <span className="text-[10px] font-mono tracking-widest text-[#ffffff70] uppercase">
                  ZOIKOVERTEX ROI ENGINE — EXECUTIVE SUMMARY
                </span>
                <span className="px-2.5 py-0.5 rounded bg-[#C9A84C]/20 text-[#C9A84C] text-[10px] font-mono uppercase">
                  Sample
                </span>
              </div>

              {/* Report Body Content */}
              <div className="p-6 sm:p-8 space-y-6">
                {/* Title & Subtitle */}
                <div className="space-y-1">
                  <h3 className="text-xl sm:text-2xl font-bold text-[#0d1017]">
                    Governed AI Execution — Business Case
                  </h3>
                  <p className="text-xs text-[#272727]/60 font-mono">
                    500-person enterprise team · Conservative scenario ·
                    Generated by ROI Engine v2.1
                  </p>
                </div>

                {/* 6 Key Metric Grid */}
                <div className="grid grid-cols-3 gap-3">
                  <div className="p-4 rounded-xl bg-[#EEF0F7] shadow-sm space-y-1 text-center">
                    <div className="text-xl sm:text-2xl font-extrabold text-[#C9A84C]">
                      $1.2M
                    </div>
                    <div className="text-[9px] font-mono text-[#272727]/60 uppercase tracking-wider">
                      ANNUAL VALUE
                    </div>
                  </div>

                  <div className="p-4 rounded-xl bg-[#EEF0F7] shadow-smspace-y-1 text-center">
                    <div className="text-xl sm:text-2xl font-extrabold text-[#1a1a1a]">
                      8 mo
                    </div>
                    <div className="text-[9px] font-mono text-[#272727]/60 uppercase tracking-wider">
                      PAYBACK
                    </div>
                  </div>

                  <div className="p-4 rounded-xl bg-[#EEF0F7] shadow-smspace-y-1 text-center">
                    <div className="text-xl sm:text-2xl font-extrabold text-[#1a1a1a]">
                      4,200
                    </div>
                    <div className="text-[9px] font-mono text-[#272727]/60 uppercase tracking-wider">
                      HRS SAVED / YR
                    </div>
                  </div>

                  <div className="p-4 rounded-xl bg-[#EEF0F7] shadow-sm space-y-1 text-center">
                    <div className="text-xl sm:text-2xl font-extrabold text-[#1a1a1a]">
                      -38%
                    </div>
                    <div className="text-[9px] font-mono text-[#272727]/60 uppercase tracking-wider">
                      APPROVAL CYCLE
                    </div>
                  </div>

                  <div className="p-4 rounded-xl bg-[#EEF0F7] shadow-sm space-y-1 text-center">
                    <div className="text-xl sm:text-2xl font-extrabold text-[#1a1a1a]">
                      +47%
                    </div>
                    <div className="text-[9px] font-mono text-[#272727]/60 uppercase tracking-wider">
                      CONTENT VELOCITY
                    </div>
                  </div>

                  <div className="p-4 rounded-xl bg-[#EEF0F7] shadow-sm space-y-1 text-center">
                    <div className="text-xl sm:text-2xl font-extrabold text-[#C9A84C]">
                      $250K
                    </div>
                    <div className="text-[9px] font-mono text-[#272727]/60 uppercase tracking-wider">
                      GOVERNANCE ROI
                    </div>
                  </div>
                </div>

                {/* Governance ROI Breakdown Card */}
                <div className="p-5 rounded-xl bg-[#C9A84C12]  space-y-3">
                  <span className="text-[10px] font-mono tracking-wider text-[#7A5A1A] font-semibold uppercase block">
                    GOVERNANCE ROI BREAKDOWN
                  </span>

                  <div className="space-y-2 text-xs">
                    <div className="flex justify-between text-[#272727]/80">
                      <span>Audit prep savings</span>
                      <span className="font-mono font-bold text-[#1a1a1a]">
                        $54K / yr
                      </span>
                    </div>
                    <div className="flex justify-between text-[#272727]/80">
                      <span>Evidence retrieval</span>
                      <span className="font-mono font-bold text-[#1a1a1a]">
                        $36K / yr
                      </span>
                    </div>
                    <div className="flex justify-between text-[#272727]/80">
                      <span>Policy exception reduction</span>
                      <span className="font-mono font-bold text-[#1a1a1a]">
                        $72K / yr
                      </span>
                    </div>
                    <div className="flex justify-between text-[#272727]/80">
                      <span>Rework cost avoidance</span>
                      <span className="font-mono font-bold text-[#1a1a1a]">
                        $88K / yr
                      </span>
                    </div>
                  </div>
                </div>

                {/* Footer Methodology Note */}
                <p className="text-[10px] leading-relaxed text-[#272727]/50 font-mono">
                  Methodology: conservative scenario. Estimates directional and
                  based on customer inputs. Not a guarantee. Full methodology
                  and assumptions available on request.
                </p>
              </div>
            </div>
          </motion.div>

          {/* Right Column: Download Form Card (5 Cols) */}
          <motion.div variants={itemVariants} className="lg:col-span-5">
            <div className="bg-white rounded-2xl p-6 sm:p-8  shadow-xl space-y-6">
              <div className="space-y-2">
                <span className="text-[10px] font-mono tracking-widest text-[#272727]/60 uppercase">
                  GET THE FULL REPORT
                </span>
                <h3 className="text-xl sm:text-2xl font-bold text-[#1a1a1a]">
                  Download the sample executive ROI report.
                </h3>
                <p className="text-xs text-[#272727]/70 leading-relaxed">
                  The full report includes methodology, assumption
                  documentation, governance value workings, and a buyer
                  justification template for internal circulation.
                </p>
              </div>

              {/* Form Inputs */}
              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-[#1a1a1a]">
                    Work email <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="email"
                    required
                    placeholder="name@company.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="w-full px-4 py-2.5 rounded-lg bg-[#f8f9fc]  text-xs text-[#1a1a1a] placeholder:text-[#272727]/40 focus:outline-none focus: transition-colors"
                  />
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-[#1a1a1a]">
                    Company
                  </label>
                  <input
                    type="text"
                    placeholder="Company name"
                    value={company}
                    onChange={(e) => setCompany(e.target.value)}
                    className="w-full px-4 py-2.5 rounded-lg bg-[#f8f9fc]  text-xs text-[#1a1a1a] placeholder:text-[#272727]/40 focus:outline-none focus: transition-colors"
                  />
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-[#1a1a1a]">
                    Your role
                  </label>
                  <select
                    value={role}
                    onChange={(e) => setRole(e.target.value)}
                    className="w-full px-4 py-2.5 rounded-lg bg-[#f8f9fc]  text-xs text-[#1a1a1a] focus:outline-none focus: transition-colors"
                  >
                    <option value="" disabled>
                      Select your role
                    </option>
                    <option value="cfo">CFO / Finance Lead</option>
                    <option value="cmo">CMO / Marketing Lead</option>
                    <option value="coo">COO / Operations Lead</option>
                    <option value="cio">CIO / IT Lead</option>
                    <option value="legal">Legal / Compliance</option>
                    <option value="procurement">Procurement</option>
                  </select>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-semibold text-[#1a1a1a]">
                    Approx. team size
                  </label>
                  <select
                    value={teamSize}
                    onChange={(e) => setTeamSize(e.target.value)}
                    className="w-full px-4 py-2.5 rounded-lg bg-[#f8f9fc]  text-xs text-[#1a1a1a] focus:outline-none focus: transition-colors"
                  >
                    <option value="" disabled>
                      Select size
                    </option>
                    <option value="50-200">50 - 200 people</option>
                    <option value="200-500">200 - 500 people</option>
                    <option value="500-1000">500 - 1,000 people</option>
                    <option value="1000+">1,000+ people</option>
                  </select>
                </div>

                <button
                  type="submit"
                  className="w-full mt-2 py-3 px-4 rounded-xl bg-[#0f1723] text-white font-semibold text-sm hover:bg-[#1a2538] transition-colors flex items-center justify-center gap-2 shadow-lg"
                >
                  <Download className="w-4 h-4" />
                  Download executive report
                </button>
              </form>

              {/* Privacy Footer */}
              <p className="text-[14px] leading-[16px] text-[#9AA3B2] text-center">
                Your details are used to prepare the report. Privacy policy
                applies. No sales calls without permission.
              </p>
            </div>
          </motion.div>
        </div>
      </motion.div>
    </section>
  );
}
